
import React from 'react';
import { 
  Activity, 
  Terminal, 
  MessageSquare, 
  FileText, 
  Settings, 
  Battery, 
  BatteryCharging, 
  Bluetooth, 
  BluetoothOff,
  Wifi,
  WifiOff,
  Mic,
  MicOff,
  Play,
  Pause,
  RotateCcw,
  Send,
  Smartphone,
  Glasses,
  Sun,
  Bell,
  BellOff,
  Zap,
  Copy,
  Download,
  Trash2,
  Check,
  MoreVertical,
  Shield,
  MapPin,
  CheckCircle,
  XCircle,
  ArrowLeft,
  Bus,
  Map,
  ArrowDown,
  Cloud,
  CloudRain,
  Thermometer,
  TrainFront,
  Wind,
  Droplets,
  Umbrella,
  CloudLightning,
  AlertTriangle,
  Info,
  ChevronDown,
  ChevronUp,
  Navigation,
  ListChecks,
  Calendar,
  Clock,
  Square,
  ToggleLeft,
  ToggleRight,
  BookOpen,
  FileSearch,
  Scroll,
  PawPrint,
  Orbit,
  Music,
  Sliders,
  TrendingUp
} from 'lucide-react';

export const BLE_UUIDS = {
  SERVICE: '6e400001-b5a3-f393-e0a9-e50e24dcca9e',
  RX_CHAR: '6e400002-b5a3-f393-e0a9-e50e24dcca9e', // Write to this (Central -> Peripheral)
  TX_CHAR: '6e400003-b5a3-f393-e0a9-e50e24dcca9e', // Receive notification from this (Peripheral -> Central)
};

export const ICONS = {
  Dashboard: <Activity size={20} />,
  Console: <Terminal size={20} />,
  Assistant: <MessageSquare size={20} />,
  Teleprompter: <FileText size={20} />,
  Settings: <Settings size={20} />,
  Battery: <Battery size={16} />,
  Charging: <BatteryCharging size={16} />,
  BluetoothConnected: <Bluetooth size={16} className="text-moncchichi-success" />,
  BluetoothDisconnected: <BluetoothOff size={16} className="text-moncchichi-error" />,
  WifiOn: <Wifi size={16} />,
  WifiOff: <WifiOff size={16} />,
  MicOn: <Mic size={20} />,
  MicOff: <MicOff size={20} />,
  Play: <Play size={20} />,
  Pause: <Pause size={20} />,
  Reset: <RotateCcw size={20} />,
  Send: <Send size={18} />,
  Phone: <Smartphone size={16} />,
  Glasses: <Glasses size={16} />,
  Brightness: <Sun size={18} />,
  SilentOn: <BellOff size={18} />,
  SilentOff: <Bell size={18} />,
  Action: <Zap size={18} />,
  Copy: <Copy size={18} />,
  Export: <Download size={18} />,
  Clear: <Trash2 size={18} />,
  Check: <Check size={18} />,
  Menu: <MoreVertical size={20} />,
  Shield: <Shield size={20} />,
  MapPin: <MapPin size={20} />,
  Bell: <Bell size={20} />,
  CheckCircle: <CheckCircle size={20} />,
  XCircle: <XCircle size={20} />,
  Back: <ArrowLeft size={20} />,
  Bus: <Bus size={20} />,
  Train: <TrainFront size={20} />,
  Map: <Map size={18} />,
  ArrowDown: <ArrowDown size={16} />,
  Sun: <Sun size={18} />,
  Cloud: <Cloud size={18} />,
  CloudRain: <CloudRain size={18} />,
  Thermometer: <Thermometer size={16} />,
  Wind: <Wind size={18} />,
  Droplets: <Droplets size={18} />,
  Umbrella: <Umbrella size={18} />,
  CloudLightning: <CloudLightning size={18} />,
  AlertTriangle: <AlertTriangle size={18} />,
  Info: <Info size={16} />,
  ChevronDown: <ChevronDown size={18} />,
  ChevronUp: <ChevronUp size={18} />,
  Navigation: <Navigation size={18} />,
  CheckList: <ListChecks size={20} />,
  Quest: <ListChecks size={20} />,
  Calendar: <Calendar size={16} />,
  Clock: <Clock size={16} />,
  Unchecked: <Square size={18} />,
  ToggleOff: <ToggleLeft size={20} />,
  ToggleOn: <ToggleRight size={20} />,
  Reader: <BookOpen size={20} />,
  Protocol: <FileSearch size={20} />,
  Codex: <Scroll size={20} />,
  PetCalc: <PawPrint size={20} />,
  Quantum: <Orbit size={20} />,
  SoundStudio: <Sliders size={20} />,
  Brokerage: <TrendingUp size={20} />
};

export const MOCK_LOGS_INIT = [
  "[SYSTEM] Initializing Moncchichi Hub...",
  "[SYSTEM] Ready for connection",
  "[INFO] Toggle 'Simulate' to switch between Real/Mock BLE"
];